### ISSUE TITLE
Cross review

### ISSUE THREAD

**Issue by sjtu-XutongLu** [LeiHaoruo/Blackjack#1]
Ten tests were all passed.

Good check procedure！
Code reuse makes your code easy and short,
You have made amazing code!
Structure is not very clear for your code.
A small mistake.From the readme, if I input 
"yaaaa", it should be rejected. sync clear the other char.

**Comment by cpxdudu** [comment]
It is a nice procedure,and there are enough notice. But if I input "yyy", then it will give me three card , and it can't judge I was lost in this situation.
